sedaprotocol/seda-chain

- cmd/seda-chaind/cmd/init.go
- cmd/seda-chaind/utils/git_download.go
So that we can init the `localnet` for integration tests.
Removed the github auth token since the `seda-networks` repo is now public.
Added `localnet` as a valid case to initing a network.
Cannot test yet blocked by https://github.com/sedaprotocol/seda-networks/pull/2.
Closes #32
> Chores: Add localnet, remove GH Auth Token

- .github/workflows/manual_test_build.yml
It's easier to onboard new developers using a CI secret instead of manually specifying allowed users.
Use a workflow dispatch input and secret variable to allow running the rest of the workflow.
CI_PASSWORD needs to be set.
Tested on a fork of this repository
Closes #12
> chore: manual deploy CI secret

- app/app.go
- scripts/local_setup.sh
- x/wasm-storage/client/cli/gov_tx.go
- x/wasm-storage/client/cli/tx.go
- x/wasm-storage/keeper/keeper.go
- x/wasm-storage/keeper/msg_server.go
This PR replaces the existing transaction endpoint for sending an `sdk.Msg` for storing an Overlay Wasm binary with a governance proposal submission endpoint that wraps this message. As a result, any updates in the Overlay Wasm bucket now require going through governance voting process. By default settings, a proposal is passed with 1/3 of voters weighted by their stakes voting and a majority yes.
Manually tested in local setting. The local setup script was updated so that voting period is short (30 seconds).
After setting up the chain with `scripts/local_setup.sh`, run the following commands to submit a proposal and vote yes.
```
$ seda-chaind tx wasm-storage submit-proposal store-overlay-wasm <wasm_file> --wasm-type relayer --title <title> --summary <summary> --deposit 10000000aseda …
```
> feat: gov-controlled Overlay Wasms

- .github/workflows/test.yml
- Makefile
To improve code quality this PR adds unit testing GH action for our repository modules
closes #55
(Link your related PRs and Issues here)
> chore(tests): Add basict test tooling

- .goreleaser.yml
- Dockerfile
In order to simplify tests and validators running the node a docker file is being created
(Write your explanation here)
(Write your test plan here)
#66
(Link your related PRs and Issues here)
> chore: add dockerfile to seda-chain

- .github/workflows/release.yml
Closes #168 
The binaries built through Docker was not showing the tag from which they were built when you run the command seda-chaind version. The GitHub workflow was not passing in the arguments to the Dockerfile correctly.
> fix: workflow fix to pass version and commit info

- app/app.go
- app/keepers/keepers.go
- app/upgrades.go
- app/upgrades/testnet/v1/constants.go
- app/upgrades/types.go
- interchaintest/chain_start_test.go
- interchaintest/chain_upgrade_test.go
- interchaintest/conformance_test.go
- interchaintest/go.mod
- interchaintest/ibc_conformance_test.go
- interchaintest/ibc_transfer_test.go
- interchaintest/setup.go
This PR attempts to achieve the followings:
- Add upgrade handler for in-place upgrades
- Add chain upgrade test
- More
⚠️ Before proceeding, make sure you change `SedaExponent` to 6 in `app/params/config.go`.  This is because in interchaintest v8.0.0 the default only has hardcoded values now which were tailored to `e6`. ⚠️
```
$ docker build --build-arg GITHUB_TOKEN=<> -t sedaprotocol/seda-chaind-e2e:old -f dockerfiles/Dockerfile.e2e . --no-cache
$ docker build --build-arg GITHUB_TOKEN=<> -t sedaprotocol/seda-chaind-e2e:new -f dockerfiles/Dockerfile.e2e . --no-cache
$ go test -timeout 10m -v -run TestChainUpgrade ./interchaintest
```
You should see the following:
```
=== RUN   TestChainUpgrade
=== PAUSE TestChainUpgrade
=== CONT  TestChainUpgrade
chain_upgrade_test.go:52: seda new …
```
> Add Upgrade Hander & Chain Upgrade E2E Test

- go.mod
- go.sum
This PR upgrades wasmvm to v1.5.2 that addresses the memory leak issue in previous versions
- https://github.com/CosmWasm/wasmvm/releases/tag/v1.5.2
- https://github.com/CosmWasm/cosmwasm/issues/1978
> Upgrade WASMVM to Include the Latest Memory Leak Fix

- app/app.go
A simple line but enables state streaming if enabled in `app.toml`.
Closes #141
> Add Support for State Streaming

- .github/workflows/interchaintest.yml
- Makefile
- app/params/config.go
- dockerfiles/Dockerfile.e2e
- interchaintest/chain_upgrade_test.go
- interchaintest/ibc_transfer_test.go
- interchaintest/setup.go
This PR adds the following e2e tests in CI:
- `TestCoreSDKCommands`
- `TestSDKBoundaries`
- `TestChainStart`
- `TestStateSync`
- `TestIBCTransfer`
- `TestPacketForwardMiddleware`
- Due to interchaintest v8 only supporting denom exponent of 6, to make the tests work we needed to change `SedaExponent` to 6 (default 18) at runtime via an environment variable. This only applies when an `SedaExponent` env var is provided (e.g. when running interchaintest). Otherwise, it simply default to 18
- `TestPacketForwardMiddleware` can be flaky and fail sometimes. If and when that happens, simply re-run it
> Add Interchaintest in CI

- README.md
- scripts/testnet/README.md
- scripts/testnet/add_wasm_state_to_genesis.sh
- scripts/testnet/build_genesis_state.sh
- scripts/testnet/config_example.sh
- scripts/testnet/members.json
- scripts/testnet/policy.json
- scripts/testnet/upload_and_start.sh
This PR adds a script for adding a group and a group policy to the genesis state. 
To achieve this, the script deploys a temporary single-node chain and sends a `create-group-with-policy` transaction based on the configurations. Afterwards, the script terminates the chain, exports the state, and injects the group state into the original genesis file. Note that the script also adds the group policy address to the wasm module's genesis parameter as the only address that is allowed to store or instantiate code.
The deployment process is still a 3-step process:
1. `create_genesis.sh` for creating genesis file and other node files.
2. `build_genesis_state.sh`, which should be run with at least one of the flags `--add-wasm-contracts` and `--add-groups`.
3. `upload_and_start.sh` to upload the …
> chore: Script for adding group to genesis state

- .github/workflows/simulations.yml
- Makefile
- app/app.go
- app/genesis.go
- simulation/helpers_test.go
- simulation/simulation_test.go
Add SDK's simulation testing that sends fuzzed transactions to the chain and tests import, export, determinism, etc.
Even though this PR only adds simulation testing for the SDK module, some customization is required mainly due to our unique aseda denom (high exponent) and our lack of support for legacy gov proposal. 
Closes: #63
> test: Add simulation test

- README.md
- cmd/sedad/cmd/root.go
- x/vesting/keeper/msg_server.go
- x/vesting/simulation/operations.go
Add a sentence in the doc advising against using Horcrux. Also closes #200
> docs: advise against Horcrux

- .github/workflows/interchaintest.yml
- Makefile
- interchaintest/ica_test.go
Adding an e2e interchain test called `TestInterchainAccounts` that tests the interchain account sub-module that our chain imports as a part of our support for IBC.
Closes: #158
> test: interchain account test

- .github/workflows/build.yml
- .github/workflows/interchaintest.yml
- .github/workflows/lint.yml
- .github/workflows/simulations.yml
- .github/workflows/test.yml
This saves some compute when frequently updating PRs.
I used the same concurrency key that most other workflows are using.
Did not test, but since this works for other workflows I'm fairly confident it will work. Famous last words...
See the GHA runs for #214, `simulation` was not cancelled while `test` and `interchaintest` were when updates were pushed in quick succession.
> Cancel simulation workflows when an update is pushed

- DEVELOPING.md
- app/app.go
- app/params/config.go
- cmd/sedad/cmd/init_cmds.go
- cmd/sedad/cmd/root.go
- e2e/e2e_gov_test.go
- plugins/indexing/bank/module.go
- scripts/testnet/create_genesis.sh
- simulation/helpers_test.go
- x/randomness/keeper/abci.go
- x/randomness/keeper/msg_server.go
- x/staking/keeper/keeper.go
- x/staking/module.go
- x/vesting/simulation/operations.go
- x/wasm-storage/keeper/msg_server_test.go
Cleaning up TODO comments.
- Avoid writing TODO comments as much as possible.
- Add an issue if possible like `TODO(#220)`
- Rename `TO-DO` to `TODO`
> chore: cleanup TODO comments

- app/params/config.go
- cmd/sedad/cmd/config_defaults.go
Set the default minimum gas prices to 10^11 aseda. Validators can tweak this local configuration value in app.toml.
> refactor: set default minimum gas prices

- .gitmodules
- DEVELOPING.md
- scripts/genesis_accounts_from_csv.sh
- scripts/genesis_accounts_from_csv_example.csv
An easy way to add genesis accounts given a csv file.
- Submodule the new seda scripts repo.
- Added a script to parse CSV and add the Genesis accounts.
- Added an example CSV file.
Any errors that occur give the failed CSV entry and the reason for failure written to the file specified.
Tested a lot by running and trying locally.
Closes #224.
> Feat: Genesis Accounts From CSV

- go.mod
- plugins/indexing/README.md
- plugins/indexing/bank/module.go
- plugins/indexing/log/logger.go
- plugins/indexing/plugin.go
- plugins/indexing/sqs/sqs_client.go
With a logger in place it's a lot easier to debug issues during development and add error monitoring in production. The 'disaster' recovery section explains which actions to take depending on where in the process the error occurred.
I looked at other Golang projects to see how they handle wrapper around libraries or do error handling so hopefully it's all rather straightforward.
I added the `abort` helper in `plugins/indexing/plugin.go` to make initialisation errors easier to process. For some reason `panic` calls do not (always?) show up in the log output of the node, but if we first log it to stdout they always show. We don't need it in the `ListenX` handlers as the errors returned from these functions are always printed in the node logs.
Logging tested by running the chain locally with …
> Plugin logging and error handling

- plugins/indexing/base/block.go
- plugins/indexing/plugin.go
I opted for a `base` package so it can house the 'base' components (blocks, TXs, validator votes). Open to suggestions for a better name. :)
You can 'just' set up the plugin, queue emulator, and start a local node. You should start seeing messages getting added to the queue:
```txt
{"level":"info","msg":"2024-03-27 07:51:17: Queue: local-updates.fifo, Message: {\"type\":\"block\",\"data\":{\"hash\":\"4B8C19CDBA69F4B032BCE5510821C9E644344BB74F76609287F4850C72F8E62F\",\"time\":\"2024-03-27T07:51:10.171833Z\",\"txCount\":0,\"proposerAddress\":\"sedavalcons1v73gscruflrq343ej403dkxcgczel6zlhpd5sg\"}}\n","time":"2024-03-27T07:51:17Z"}
```
Just the message:
```json
{
"type": "block",
"data": {
"hash": "4B8C19CDBA69F4B032BCE5510821C9E644344BB74F76609287F4850C72F8E62F",
"time": …
```
> Publish block data

- plugins/indexing/base/transaction.go
- plugins/indexing/plugin.go
The main thing I'm unsure about is how we pass the codec around, is this idiomatic Golang or is there a cleaner way to do this?
Made a small improvement in the `ListenFinalizeBlock` handler by preallocating the slice since we should know up front how long it is going to be.
You can 'just' set up the plugin, queue emulator, and start a local node. Once it's running submit a transaction (for the example I used a bank transfer, but I have tried a bunch of different ones). You should start see a `"tx"` message getting added to the queue:
```json
{"level":"info","msg":"2024-03-27 17:23:39: Queue: local-updates.fifo, Message: {\"type\":\"tx\",\"data\":{\"hash\":\"1D3D58C0F82BCDFC1B4A2FDC43CD73C9DC6EC5C48AB78265072736A21B9A2392\",\"time\":\"2024-03-27T17:23:31.469443Z\",\"tx\":{\"body\":{\"messag …
```
> Publish tx data

- README.md
Adding a section in the README on how to join testnet using snapshot provided by Lavender.Five Nodes.
> doc: add doc on joining testnet using snapshot

- README.md
Updating Lavender.Five's snapshot link.
We will rely on this until we provide snapshots ourselves.
> doc: update Lavender.Five snapshot link

- plugins/indexing/auth/module.go
- plugins/indexing/plugin.go
Marshalling with the interface gives us an identifier for the account type, which we can use on the indexer side to know how to unpack the object.
You can 'just' set up the plugin, queue emulator, and start a local node. When it starts you should see all the genesis accounts being indexed in block 1:
```json
{"level":"info","msg":"2024-04-08 11:26:55: Queue: local-updates.fifo, Message: {\"type\":\"account\",\"data\":{\"@type\":\"/cosmos.auth.v1beta1.ModuleAccount\",\"base_account\":{\"address\":\"seda1fl48vsnmsdzcv85q5d2q4z5ajdha8yu3r49h6k\",\"pub_key\":null,\"account_number\":\"7\",\"sequence\":\"0\"},\"name\":\"bonded_tokens_pool\",\"permissions\":[\"burner\",\"staking\"]}}\n","time":"2024-04-08T11:26:55Z"}
{"level":"info","msg":"2024-04-08 11:26:55: Queue: local-updates.fifo, Message: …
```
> Publish account data

- plugins/indexing/auth/module.go
- plugins/indexing/bank/module.go
- plugins/indexing/base/block.go
- plugins/indexing/base/transaction.go
- plugins/indexing/plugin.go
- plugins/indexing/sqs/sqs_client.go
- plugins/indexing/types/block_context.go
- plugins/indexing/types/message.go
Also refactor SQS publishing to allow messages to carry the associated block height and time.
Run the chain and plugin locally and verify the messages on the queue have the correct attributes:
```sh
aws --endpoint-url http://localhost:4100 sqs receive-message --queue-url http://localhost:4100/local-updates.fifo --attribute-names height,time
{
"Messages": [
{
"MessageId": "3e9eb3a0-7030-47f0-961e-745e6d8a5583",
"ReceiptHandle": "3e9eb3a0-7030-47f0-961e-745e6d8a5583#8921b4ff-5b42-40ef-b404-07d31e2ce536",
"MD5OfBody": "e88e931a689f0ee2939ab27c3dc51f4f",
"Body": "{\"type\":\"block\",\"data\":{\"hash\":\"8223F5B02B59C3BE888C215CB1FA0BDA3B2194E873BD9B74A4BED6B51A5489FC\",\"time\":\"2024-04-10T19:35:15.116228Z\",\"txCount\":0,\"proposerAddress\":\"sedavalcons1gnl65ayhvetqjm42ynxwlkv7g93w0h4a5rvuu …
```
> Publish timestamp

- plugins/indexing/bank/module.go
Since these entries just get deleted from the store we have to manually set the published amount to 0.
I added a genesis account with `20000000000000001aseda` as balance and then delegated `1aseda` to the local validator with a fee of `20000000000000000aseda`, which leaves the account with `0aseda` as balance.
Observing the log output and published messages when running locally:
Log before:
```
2024-04-11T13:40:00.720+0200 [DEBUG] Extracted update: message="&{0x1400065e400 account-balance {seda12rype4zl8wxcgqwl237fll6hvufkgcj8kwnuah <nil> aseda}}"
```
Log after:
```
2024-04-11T13:32:32.354+0200 [DEBUG] Extracted update: message="&{0x14000f318e0 account-balance {seda12rype4zl8wxcgqwl237fll6hvufkgcj8kwnuah 0 aseda}}"
```
Queu message before:
```json
{
"type": "account-balance",
"data": { …
```
> Correctly format balance updates with 0aseda

- go.mod
- go.sum
Upgrading ibc-go to v8.2.0, which includes a fix to a critical bug https://github.com/cosmos/ibc-go/releases/tag/v8.2.0
> chore: upgrade ibc-go to v8.2.0

- plugins/indexing/base/block.go
- plugins/indexing/plugin.go
Enable the indexer to add events to a block which will ultimately allow the frontend to display these to the user.
N.A.
I tried submitting a bunch of different transactions (CosmWasm code upload, transfers, create validator) and none of the TX events also showed up in the block events output as expected.
Running the chain and plugin locally you can see that the events are now part of the serialised message on the queue:
```json
{
"type": "block",
"data": {
"hash": "6B0E2CBB389B276049E5AF9C5D2EC248756B699507643157B8A093F1A1020D2E",
"time": "2024-05-02T09:38:17.150989Z",
"txCount": 1,
"proposerAddress": "sedavalcons1gapnqg6u8wkjm3et7qd3j8l3vkftukt52qfjmg",
"events": [
{
"type": "coin_received",
"attributes": [
{
"key": "receiver",
"value": "seda1m3h30wlvsf8llruxtpukdvsy0km2kum87ltqyp", …
```
> feat(plugin): publish block event data

- plugins/indexing/README.md
- plugins/indexing/pluginaws/message_filter.go
- plugins/indexing/pluginaws/sqs_client.go
- plugins/indexing/pluginaws/types.go
Make indexing previously indexed state easier by skipping messages that have already been indexed.
Optionally allow configuring a list of message types that are allowed to be published on the queue. Went for an allowlist as we'll generally use it when we want to reindex historical state and only publish updates for the new messages.
For the same reason I went for a simple slice of strings as the data structure; the list should never be long enough to matter in terms of performance.
Ran a local chain with the messages allowlist attribute set to `account,account-balance`
Logs:
```log
2024-05-15T18:00:34.456+0800 [TRACE] publishing to queue: size=4
2024-05-15T18:00:34.456+0800 [TRACE] skipping message: type=supply
2024-05-15T18:00:34.456+0800 [TRACE] sending batch: size=3
```
And on the …
> Add message filtering capability

- plugins/indexing/pluginaws/aws_session.go
- plugins/indexing/pluginaws/aws_session_dev.go
- plugins/indexing/pluginaws/custom_retryer.go
Every once in a while the indexing plugin receives a connection rest while attempting to upload a large message to S3. This halts the indexing process as there are some cases where an error in the indexer warrants a reset to the previous block. By default the retry logic from the AWS SDK does not retry on connection resets as it can't know whether the request that was made is idempotent or not.
Based on some reading:
PR trying to 'fix' that the SDK no longer retries connection reset errors: https://github.com/aws/aws-sdk-go/pull/2926
How to determine the error: https://github.com/aws/aws-sdk-go/blob/v1.44.224/aws/request/connection_reset_error.go
Custom retryer example: https://github.com/aws/aws-sdk-go/blob/main/example/aws/request/customRetryer/custom_retryer.go
Since we know that the …
> Add retry to S3 connection reset errors

- plugins/indexing/plugin.go
- plugins/indexing/staking/module.go
This includes messages for the validator information, power, delegations, unbonding delegations, redelegations, and staking module parameters.
Reasonably straightforward code. The delete entry for some values requires us to process the event differently, but even that is not too fancy.
Running a local chain with the following changes to the genesis to facilitate testing:
```sh
cat $HOME/.sedad/config/genesis.json | jq '.app_state["staking"]["params"]["unbonding_time"]="30s"' > $HOME/.sedad/config/tmp_genesis.json && mv $HOME/.sedad/config/tmp_genesis.json $HOME/.sedad/config/genesis.json
cat $HOME/.sedad/config/genesis.json | jq '.app_state["slashing"]["params"]["signed_blocks_window"]="30"' > $HOME/.sedad/config/tmp_genesis.json && mv $HOME/.sedad/config/tmp_genesis.json …
```
> Publish staking module messages

- go.mod
- go.sum
Upgrade tally vm to v1.0.1, which includes a fix for static library for ARM architecture.
> chore: Upgrade tally vm

- plugins/indexing/base/block.go
Removed all events with empty amount attribute value from the ResponseFinalizeBlock events.
Closes: #302
> chore(plugin): discard block events with empty amount attribute

- plugins/indexing/README.md
- plugins/indexing/pluginaws/sized_batch_entry.go
Reduce costs, simplify implementation, easier error handling.
Essentially did the reverse of the AWS instructions for moving to a FIFO queue: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-moving.html
Ran the chain + plugin locally and confirmed the messages still end up in the local queue emulator.
Closes: #233
> Move to regular queue

- scripts/testnet/create_genesis.sh
- x/wasm-storage/keeper/keeper.go
Fixes the export panic when the core contract registry is empty.
> fix: Export genesis fix

- Makefile
- cmd/sedad/cmd/root.go
- cmd/sedad/cmd/rosetta_disabled.go
- cmd/sedad/cmd/rosetta_enabled.go
Adding an optional build tag called `rosetta` to determine whether to add Rosetta support or not.
To build with this tag using make, run:
```
ENABLE_ROSETTA=true make build
```
Related: #298 
Thank you @Thomasvdam for the solution!
> fix: Adding build tag for Rosetta

- x/data-proxy/keeper/common_test.go
- x/data-proxy/keeper/grpc_query.go
- x/data-proxy/keeper/grpc_query_test.go
- x/data-proxy/keeper/keeper.go
- x/data-proxy/keeper/msg_server_test.go
- x/data-proxy/module.go
- x/data-proxy/types/errors.go
Give the user better feedback when a public key does not have an associated data proxy config registered.
Not much, just updating what was already there from the boilerplate, adding tests, and making the error a little more user friendly when an unknown public key is queried.
Added tests for the query server.
Part-of: #316
> chore(data-proxy): update proxy query not found error

- x/data-proxy/keeper/abci.go
- x/data-proxy/keeper/msg_server.go
- x/data-proxy/types/events.go
Easier to see in the explorer what the effects were of a transaction or endblock state mutation.
Followed the example from other modules (tally and wasm-storage).
N.A.
Part-of: #316
> Emit data-proxy events

- x/data-proxy/keeper/msg_server.go
- x/data-proxy/keeper/msg_server_test.go
- x/data-proxy/types/errors.go
- x/data-proxy/types/params.go
- x/data-proxy/types/proxy_config.go
- x/data-proxy/types/tx.go
Make errors more in line with the changes introduced in #333 and adds additional validation on TXs.
We decided to check the denom through the appparam const as it seems that changing the denom in the staking keeper wouldn't work anyway.
Add unit tests to verify that param changes don't affect pending updates.
Part-of: #316
> Additional validation and improved errors

- Makefile
- app/app.go
- e2e/e2e_gov_test.go
- interchaintest/chain_core_test.go
- interchaintest/chain_upgrade_test.go
- interchaintest/state_sync_test.go
- plugins/indexing/data-proxy/module.go
- plugins/indexing/plugin.go
- simulation/helpers_test.go
- x/data-proxy/keeper/msg_server_test.go
- x/tally/keeper/filter_fuzz_test.go
- x/tally/types/filters.go
- x/wasm-storage/keeper/msg_server_test.go
Targeting the wasm expiration branch to make merging simpler.
Publish changes in the data-proxy store on the SQS queue.
Also updated the linter as it was complaining about dependencies, but then it started complaining about some existing code so I had to fix that.
Ran plugin locally and tested registering a proxy, editing a proxy (new memo, new fee), and transferring the admin address.
Example message:
```json
{
"type": "data-proxy",
"data": {
"pubKey": "034c0f86f0cb61f9ddb47c4ba0b2ca0470962b5a1c50bee3a563184979672195f4",
"config": {
"payout_address": "seda1wyzxdtpl0c99c92n397r3drlhj09qfjvf6teyh",
"fee": { "denom": "aseda", "amount": "10000000000000000000" },
"memo": "test me sedaddy",
"admin_address": "seda1wyzxdtpl0c99c92n397r3drlhj09qfjvf6teyh",
"fee_update": {
"new_fee": { "denom": …
```
> Publish data proxy messages

- plugins/indexing/data-proxy/module.go
Because the old implementation is simply wrong.
N.A.
Ran locally to verify it's no longer publish as `staking`....
N.A.
> Correct the module name in data-proxy params messages

- go.mod
- go.sum
Upgrading tally vm dependency to v1.1.3
Due to problems with the artefacts of v1.1.1 and v1.1.2 those builds will not work on an x86 machine with dynamic linking.
Closes: #359
> chore: Upgrade tally vm to v1.1.3

- plugins/indexing/plugin.go
- plugins/indexing/pluginaws/aws_session.go
- plugins/indexing/pluginaws/aws_session_dev.go
- plugins/indexing/pluginaws/custom_retryer.go
- plugins/indexing/pluginaws/types.go
See #362 
Make it easier to apply the retry logic to different configs, and the config to the SQS client.
Also disable the staking messages in the plugin. Before we kept an allowlist of message types that didn't include anything from the staking module, but as it'll probably be a while before we add support for those I figure it's easier to just disable the functionality at the plugin level.
Confirm messages still get sent locally. Difficult to trigger a connection reset error locally though, but worst case it doesn't retry which is the same behaviour we have right now.
Closes: #362
> Add connection reset retry to SQS

- plugins/indexing/oracle-program/module.go
- plugins/indexing/plugin.go
Allow the explorer to display a list of uploaded Oracle Programs as well as the status and expiration height (if set).
We take the bytecode from the store as this simplifies the indexing process, despite also having the bytecode in the original transaction.
Used the oracle-program name to be a little bit more future proof 😅 
Ran the chain locally with SQS and S3 emulators.
After uploading a WASM we get the following event:
```json
{
"type": "oracle-program",
"data": {
"id": "605244b203c3039b0c3d61821cf9147f4c76fa137054ac72c74d6f1a6864e56b",
"bytecode": "<BYTES>",
"addedAt": "2024-09-30T15:08:05.836221Z",
"expirationHeight": 0
}
}
```
And for the parameters we get:
```json
{
"type": "module-params",
"data": {
"moduleName": "oracle-program-storage",
"params": { "max_wasm_size": 819200, …
```
> Publish oracle program events

- go.mod
- go.sum
- x/tally/types/filters.go
Staying up to date.
Since the local emulator now supports the new JSON API we no longer have
to use the old SDK version.
Running the chain and plugin locally with the new emulator publishes messages as expected.
https://github.com/sedaprotocol/seda-explorer/pull/525
> Update aws SDK

- plugins/indexing/batching/module.go
- plugins/indexing/plugin.go
Support indexing results.
Reimplement the struct to avoid having to deal with the `omitempty` tags on the receiving end.
Add code in `x/tally/keeper/abci.go` that inserts a dummy result every block.
Run the chain and plugin locally with a queue emulator, messages get published with the following JSON:
```json
{
"type": "data-result",
"data": {
"result_id": "74",
"dr_id": "74",
"version": "1",
"block_height": 74,
"exit_code": 0,
"gas_used": 0,
"result": "eyJyZXN1bHQiOiAiMSJ9",
"payback_address": "1",
"seda_payload": "1",
"consensus": true
}
}
```
Closes: #371
> Publish data result events

- app/app.go
- proto/sedachain/batching/v1/genesis.proto
- proto/sedachain/batching/v1/query.proto
- x/batching/client/cli/query.go
- x/batching/keeper/abci_test.go
- x/batching/keeper/data_result.go
- x/batching/keeper/endblock.go
- x/batching/keeper/genesis.go
- x/batching/keeper/keeper.go
- x/batching/keeper/querier.go
- x/batching/types/genesis.go
- x/batching/types/genesis.pb.go
- x/batching/types/keys.go
- x/batching/types/query.pb.go
- x/batching/types/query.pb.gw.go
- x/tally/types/filters.go
This PR adds a new mapping from data request ID to batch number. This "batch assignment" is created when during the batching end blocker's data result tree construction.
Also adds query endpoints for a data result given the associated data request ID and for an assigned batch number given the associated data request ID.
Closes: #379
> feat (batching): batch number assignment and data result query

- plugins/indexing/base/block.go
- plugins/indexing/base/transaction.go
- plugins/indexing/plugin.go
Make explorer go brrrr.
We'll extract the data from the store once we want to publish it so we can safely skip the bytes in the transaction parsing.
Tested on the planet deployment, see https://planet.test.explorer.seda.xyz/pr/feat-planet/blocks. Block 100 caused the crash originally since that was the height where vote extension were enabled.
N.A.
> Skip vote extension bytes in RequestFinalizeBlock

- plugins/indexing/batching/module.go
Prevent bugs when the block height or gas used gets too high.
Since we're using a JS implementation on the other we need to format the values as string to prevent incorrect deserialisation.
Run the chain and plugin locally with a modified tally abci.go that always writes results.
Follow up on #382
> Convert uint64 to string

- .gitattributes
- app/abci/handlers.go
- scripts/local_multi_setup.sh
The batch signature verification in `ProcessProposal` would occasionally fail because the last commit information contains votes that lack corresponding pre-commit votes and, as a result, batch signatures. This PR resolves the issue by ensuring that only batch signatures from votes with pre-commit votes are verified.
Improved local multi-node test script and simulated a chain until block 100. 
Closes: #388
> fix (batching): only consider batch signatures from votes with `BlockIDFlagCommit`

- scripts/deploy_contracts.sh
Kind of an edge case but when trying to redeploy the same contract with different constructor arguments the script fails.
It turns out that the label, code ID, and owner don't matter much with the predictable address generator and we need to pass a new salt if we want to reupload the same contract with different instantiation arguments.
Used in the planet redeployment of the contract.
N.A.
> Update core contract deploy script

- plugins/indexing/batching/module.go
Allow showing batches in the explorer.
We'll unpack the validator tree entry on the indexer side. This should make it so we don't have to update the plugin when we add additional signature schemes.
Run the chain and plugin locally, with an edit in `x/tally/keeper/abci.go` to publish a fake result every 10th block.
- `batch` event
```json
{
"type": "batch",
"data": {
"batch_number": "1",
"block_height": "1",
"data_result_root": "9c6b2c1b0d0b25a008e6c882cc7b415f309965c72ad2b944ac0931048ca31cd5",
"validator_root": "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
"batch_id": "f58c797327c8db6eb2e616316f33046e4a8f1b17eadc29f461e3002081865f19",
"proving_medatada": ""
}
}
```
- `dr-batch-assignment` event
```json
{
"type": "dr-batch-assignment",
"data": { "dr_id": "10", …
```
> Publish batch events

- plugins/indexing/batching/module.go
This would have been nice in the initial PR as it allows us to show some details about the batch in the explorer.
N.A.
Ran locally during the last PR, just forgot to unstash and commit the changes...
Part-of: #372
> Publish batch validator entry events

- app/abci/handlers.go
Allow correlating a vote to the validator that cast it.
The address bytes in the extended commit info are for the consensus public key, not the validator public key.
Run the chain locally and confirm the address that gets written to store matches the address of the validator when querying the staking module.
N.A.
> Store correct validator operator address

- app/abci/handlers.go
- app/abci/vote_extension_test.go
- app/utils/seda_keys.go
- x/batching/keeper/endblock.go
- x/batching/types/data_result.go
- x/tally/keeper/abci.go
- Use geth library for signing so that the public key can be recovered from the signature.
> refactor(x/batching): use geth library for ECDSA signing

- x/batching/keeper/endblock.go
Hashes mismatch
Change dataRoot to superRoot in batch id calculation
> fix(batching): fix issue where hash used dataRoot instead of superRoot

- plugins/indexing/oracle-program/module.go
- scripts/deploy_contracts.sh
Allow indexing the current core contract. Useful when we're debugging on planet/devnet.
N.A.
With the local chain, plugin, and emulator setup the following message gets published when the contract is instantiated and registered:
```json
{
"type": "core-contract",
"data": {
"contractAddress": "seda15yelgw73s2r48lp9x57d6h9jzh6est34zkcchvxa3q9eax2g8jxq055jcd"
}
}
```
Somewhat related to the [events update in the chain contracts](https://github.com/sedaprotocol/seda-chain-contracts/pull/226).
> Publish core contract address

- plugins/indexing/pluginaws/types.go
An empty variable should also allow all message types to be sent.
N.A.
Ran locally with `./scripts/local-setup.sh --plugin`
N.A.
> Handle empty message filter env variable

- dockerfiles/Dockerfile.build-static
- dockerfiles/Dockerfile.static
Fix issue where the CI release builds were unable to correctly determine which tallyvm version to download. 
N.A.
N.A.
N.A.
> Update dependency path for tallyvm version extraction

- app/app.go
- x/batching/keeper/integration_test.go
- x/tally/keeper/integration_test.go
- x/tally/module.go
- x/tally/types/codec.go
- x/tally/types/genesis.go
- x/tally/types/params.go
Without the default genesis state the module ends up in a state where it can't retrieve the max gas limit and all tally executions will just error out. See https://planet.test.explorer.seda.xyz/data-requests/72a0a8a68247202079023a800ef69c742e73fab43dff579bd2229cb5457ca622/894 for an example error.
Also register the message server and interfaces in the app module so we can actually update the params through governance. :)
Implement genesis methods in the module.
Run a local chain with code added in the tally endblock handler to print the max gas limit every block. 
```json
{"level":"info","module":"server","module":"x/tally","max_gas_limit":300000000000000,"time":"2024-12-10T15:12:24+01:00","message":"max tally gas limit"}
```
N.A.
> Add default genesis state

- go.mod
- go.sum
Upgrading iavl dependency to v1.2.2 which includes the fix for #414.
Closes #414
> Upgrade iavl dependency

- x/tally/keeper/abci.go
- x/tally/types/errors.go
When an error occurs in FilterAndTally(), we now log the error details for debugging purposes and return simplified error information to be stored as part of the data results.
Closes #430
> Improve tally error handling

- scripts/local_setup.sh
Make it easy to interact with a local chain through browser extensions without having to deal with HTTP proxies.
Rather than introducing a new flag I lumped it with the existing `--plugin` flag, as for most cases we'll want to use them in tandem. Should it turn out to be useful separately we can always move it to its own flag.
Similar to the setup described in #442, but now we don't need a HTTP proxy and can directly point the browser extension to the local address and port.
N.A.
> Allow all CORS requests when running locally with plugin

- x/data-proxy/keeper/common_test.go
- x/data-proxy/keeper/msg_server.go
- x/data-proxy/keeper/msg_server_test.go
When registering a data-proxy we now require the signed payload to include the chain-id for the intended network. This prevents replay attacks between different environments.
Also updated the invalid signature error to more clearly specify it's the data proxy signature that's invalid, not the TX signature.
Updated the test vectors by running `bun run start register <ADDRESS> <AMOUNT> -n mainnet` in the SEDA data proxy PR: https://github.com/sedaprotocol/seda-data-proxy/pull/38
Closes: #455
> Include chain-id in signature payload

- app/ante.go
- app/app.go
I feel like this code can definitely be better, so open to suggestions on how to better split it up to make it more maintainable/testable :)
Executor nodes should not have to pay for performing their duties in the protocol. The antehandler verifies that all messages in a transaction are commits and/or reveals which are eligible before allowing a gas price of 0 for the transaction.
We're wrapping the antehandler from CosmWasm and manually prepending our antehandler as this way we don't have to maintain the decorator list ourselves.
I'm not quite sure how we can add unit/integration tests for this as it requires a whole bunch of keepers :(
I tested it with a local chain and a contract built from https://github.com/sedaprotocol/seda-chain-contracts/commit/aa0a52f339d1bd1ddc30e6d344b4c96de12e5 …
> Allow free gas for eligible commit/reveal messages

- app/utils/seda_signer.go
Annoying workaround for the tempApp issue.
To work around the tempApp that the CLI creates and doing validation on the presence of a encryption key we forced the allow unencrypted key files flag in the tempApp call. This causes problems when you also set the encryption key as en env variable. As we can't easily know if we're in the temp App flow or the actual app we decided to skip this check for now...
Verified that TXs failed to create locally when the env var was set before the fix, and that it works now with the fix.
Fixes issue introduced in: #468
> Allow encryption key with allow-no-encryption flag set

- x/tally/keeper/endblock.go
- x/tally/keeper/tally_vm.go
- x/tally/types/abci_types.go
- x/tally/types/data_result.go
I'm the least sure about the fallback values. In the end I decided to just write the values we got from the contract to the store, instead of redoing all the encoding checks to figure out what was wrong. 
Main difference is that we now allow the node to panic if we are unable to write to the store. This prevents us from continuing on invalid state should something go wrong there. It should never happen due to inputs as those get validated at mutliple points throughout the code.
We also write an empty result to the store in case there are encoding/decoding errors for fields that we are in control of.
N.A.
Tests still work, no panics yet as this shouldn't really happen anyway :)
N.A.
> chore(x/tally): update endblock error handling

- go.mod
- go.sum
No longer crash on certain Oracle Programs.
N.A.
Handled in the wasm-vm repository.
https://github.com/sedaprotocol/seda-wasm-vm/pull/54
> Update tallyvm to v2.2.2

- x/tally/keeper/endblock.go
- x/tally/types/errors.go
Distinguish between unexpected errors when executing the expire DR message and an expected error from when the contract is paused.
I think there is not much else we can do apart from checking the error string.
Built the contract from https://github.com/sedaprotocol/seda-chain-contracts/pull/257, spun up a local chain and deployed the contract using the script in this repository. Paused the contract:
```
sedad tx wasm execute seda1gj9cxtatghehj5z57seq7mge7342gzwxu6wz42l96pf3urygjjrs0hvrmh '{"pause":{}}' --from satoshi --keyring-backend test --gas auto --gas-adjustment 1.5 --gas-prices 10000000000aseda
```
Monitor logs and observed:
```
{"level":"warn","module":"server","module":"x/tally","time":"2025-01-29T11:08:33+01:00","message":"Contract is paused, skipping tally end block"}
``` …
> Detect paused core contract and print warning

- cmd/sedad/cmd/root.go
Fixing the mistake that was introduced in #398. This was causing an error when exporting the state.
> Fix wasm directory setup for export

- go.mod
- go.sum
Addresses [CWA-2025-001](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2025-001.md) and CWA-[2025-002](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2025-002.md).
Only update the dependency. According to the changelog there are no further changes required.
Tests still pass.
N.A.
> Update wasmvm to 2.1.5

- .github/workflows/build.yml
- x/tally/keeper/gas_meter.go
- x/tally/keeper/gas_meter_test.go
- x/tally/keeper/integration_test.go
We encountered a bug on planet where a reduced payout scenario resulted in ALL funds being burnt with nothing left over for the data proxies or executors. This is not very fair.
No longer multiply the reduced burn amount (gas) with the gas price twice.
Added a manual test for the exact reproduction scenario and changed the fuzz test to also do a sanity check that reduced payout only changes where funds are allocated and no increase/decrease in the total.
N.A.
> Increase burn amount with correct number in reduced payout

- x/tally/README.md
- x/tally/keeper/endblock.go
- x/tally/keeper/filter.go
- x/tally/keeper/filter_and_tally_test.go
- x/tally/keeper/filter_test.go
- x/tally/keeper/gas_meter.go
- x/tally/keeper/gas_meter_test.go
We now provide an outlier list when we calculate executor payouts so that outliers do not receive execution payouts. Note that this outlier list is `nil` in the following three filter outcomes:
- No basic consensus
- No consensus
- Filter input error
> No executor payout to outliers

- x/wasm-storage/keeper/msg_server.go
- x/wasm-storage/keeper/msg_server_test.go
Adding authority when instantiating core contract so that only governance module can invoke the message handler.
> Add authority check when instantiating core contract

- .golangci.yml
- plugins/indexing/plugin.go
- plugins/indexing/pubkey/module.go
- plugins/indexing/tally/module.go
- plugins/indexing/types/js_json_marshal.go
Allow the indexer to process this data.
Also removed deprecated golangci lint settings so the pipeline stops yelling at me.
The following JSON messages get published on the SQS queue:
```js
{
type: "module-params",
data: {
moduleName: "tally",
params: {
burn_ratio: "0.200000000000000000",
execution_gas_cost_fallback: "5000000000000",
filter_gas_cost_multiplier_mode: "100000",
filter_gas_cost_multiplier_std_dev: "100000",
filter_gas_cost_none: "100000",
gas_cost_base: "1000000000000",
max_result_size: 1024,
max_tallies_per_block: 100,
max_tally_gas_limit: "50000000000000",
},
},
}
```
```js
{
type: "module-params",
data: {
moduleName: "pubkey",
params: {
activation_block_delay: "11520",
activation_threshold_percent: 80,
},
},
}
```
```js
{
type: "proving-scheme",
data: { index: 0, …
```
> Publish pubkey and tally data

- .github/workflows/release.yml
- e2e/chain.go
- e2e/e2e_register_core_contract_test.go
- e2e/e2e_setup_test.go
- e2e/e2e_test.go
- e2e/e2e_unbond_test.go
- e2e/query.go
Since simulation testing does not involve the ABCI consensus process, we need to resort to the e2e test to test the complete sequence of ABCI methods we use for batch signing.
This PR adds two unbond transactions to the e2e to trigger creation of batches. The test waits until the number of signatures collected for each batch equals to the number of validators.
> Basic batch signing testing through e2e test

- scripts/local_multi_setup.sh
- scripts/local_setup.sh
Make it easier to locally test a multi validator network setup.
Fixes overlapping ports and makes the genesis file more similar to what we use in the single node setup.
Run the script locally and check that all the validators get created and batches are created and signed.
N.A.
> Update local multi setup

- e2e/e2e_batch_key_rotation_test.go
- e2e/e2e_test.go
- e2e/e2e_unbond_test.go
- e2e/query.go
This adds a test that hopefully confirms our implementation is correct for the batch signing key rotation.
Test in a 2 validator network with both validators starting at 50% voting power.
Record the eth address of validator 1.
Rotate the key of validator 1.
Confirm a new batch is created and that it has a new eth address for validator 1.
Trigger a new batch creation.
Confirm that this new batch is signed by both validators.
This test does not guarantee that the signature verification is implemented correctly, but in the case that it is it proves that a validator correctly signs the batch after rotation with their **old** key, and only the next batches get signed with the **new** key.
It's just a test.
Targeting other PR to simplify merging.
> Add e2e test for batch signing when 1/3rd of voting power rotates keys

- app/abci/testutil/tx_verifier_mock.go
- app/abci/vote_extension_test.go
- app/app.go
- app/params/config.go
- cmd/sedad/cmd/config_defaults.go
The NoOpMempool accepts any transactions proposed by the proposer and does not do any validation, see https://github.com/cosmos/cosmos-sdk/blob/v0.50.12/baseapp/abci_utils.go#L385. By switching to a different mempool and making sure the bytes which are not valid TXs are not validated we can get the best of both worlds.
Due to an error in the default config prior to https://github.com/cosmos/cosmos-sdk/pull/20008 it seems most of our validators will have a setting for the MaxTs which results in the SenderNonceMempool being selected: https://github.com/cosmos/cosmos-sdk/blob/v0.50.12/server/util.go#L544. Looking at our testnet and mainnet nodes I can confirm that the `max-txs` attribute in the `config/app.toml` is set to `5000`
For these reasons I think we should be fine with the …
> Use SenderNonceMempool

- app/abci/errors.go
- app/abci/handlers.go
- app/abci/vote_extension_test.go
- x/pubkey/keeper/endblock.go
- x/pubkey/keeper/endblock_test.go
- x/tally/types/gas_meter.go
This PR addresses several issues identified during the audit:
- Consume remaining tally gas in an out of gas case.
- Check that the number of transactions in a proposal is not zero to avoid panics in `ProcessProposal` and in `PreBlocker`.
- When we jail validators without the required keys during proving scheme activation, ensure that they have not already been jailed to avoid an error.
> Consume remaining tally gas in out of gas case

- x/data-proxy/keeper/common_test.go
- x/data-proxy/keeper/msg_server.go
- x/data-proxy/keeper/msg_server_test.go
- x/data-proxy/types/proxy_config.go
- x/data-proxy/types/tx.go
Noone like front running unless it means they're only paying for your gas.
Require the signer address to be part of the signed payload.
Updated test vectors with data from https://github.com/sedaprotocol/seda-data-proxy/pull/41
Data proxy PR: https://github.com/sedaprotocol/seda-data-proxy/pull/41
> Prevent frontrunning data proxy registration

- app/abci/handlers.go
- app/abci/helpers_test.go
- app/abci/utils.go
- app/abci/vote_extension_test.go
Since votes that arrive before the commit timeout but after the block has been delivered to the application are not verified with the verifyVoteExtension handler we need to account for potentially invalid votes in the prepareProposalHandler. Since we at least are guaranteed to receive verified votes for over 2/3rds of voting power we can simply ignore any vote that was invalid.
Most of the VoteExtension code is taken directly from skip-mev/connect https://github.com/skip-mev/connect/blob/main/abci/ve/vote_extension.go, which in turn is taken almost directly from the SDK https://github.com/cosmos/cosmos-sdk/blob/v0.50.13/baseapp/abci_utils.go.
Refactored the tests significantly to make every individual test a little more clear, since the malicious proposer scenario adds so many variations …
> fix(abci): handle invalid vote extensions in late votes

- x/tally/keeper/endblock.go
- x/tally/types/abci_types.go
This check is technically unnecessary since the contract imposes the minimum gas price at 1000.
> Positive gas price check for reassurance

- app/abci/handlers.go
- app/abci/vote_extension_test.go
Since the EVM contract require signatures to be in the low-s form a malicious proposer could prevent a batch from being submitted by injecting the high-s form of signatures in a proposal. Without this change these signatures would pass the `verifyBatchSignatures` check.
I only modified the verification since our signatures should be in the low-s form since the library we're using normalises the signature: https://github.com/bitcoin-core/secp256k1/blob/70f149b9a1bf4ed3266f97774d0ae9577534bf40/src/ecdsa_impl.h#L294.
Tests still pass, although one with a different error.
N.A.
> Require batch signatures to be in low-s form

- x/data-proxy/keeper/keeper.go
- x/data-proxy/keeper/msg_server.go
- x/data-proxy/keeper/msg_server_test.go
- x/data-proxy/types/errors.go
- x/data-proxy/types/params.go
Targeting other PR for easier merging.
As discussed it should be super unlikely that any number of data proxies schedule their update for the same block, and even if a large number needs to be coordinated it shouldn't matter that they need to be spread out over a few blocks.
The value 25 was randomly decided so I'm open to other values. I went with this since it's low enough that iterating doesn't matter but high enough to allow for some random collisions.
Added a unit test to verify that scheduling an update isn't possible once the max is reached, but becomes possible again once an update is rescheduled.
N.A.
> Limit the amount of data proxy fee updates per block

- x/pubkey/keeper/msg_server.go
- x/pubkey/keeper/msg_server_test.go
- x/pubkey/types/events.go
- x/pubkey/types/tx.go
Make it easier to trace a chain of pubkeys when a validators rotates them.
N.A.
Added a unit test to verify the correct events are emitted.
N.A.
> Emit rotated pubkey

- x/tally/keeper/filter_and_tally_test.go
- x/tally/keeper/gas_meter.go
- x/tally/keeper/gas_meter_test.go
- x/tally/types/gas_meter.go
- x/tally/types/hash_sort.go
- x/tally/types/hash_sort_test.go
We want to prevent executors/proxies with keys that sort favourably from obtaining rewards more often in the unlikely case where there is not enough aseda in escrow to reward all the participants.
I opted to use the bytes of the string representation so we don't have to deal with decoding the strings as hex.
We use the data request id and the block height at which the request is tallied as entropy to add together with the public key to produce a hash which we use for sorting.
Added unit tests for the 
N.A.
> Data proxy and executor pubkey sorting

- x/tally/keeper/endblock.go
- x/tally/keeper/filter.go
- x/tally/keeper/filter_and_tally_test.go
- x/tally/keeper/filter_test.go
- x/tally/keeper/gas_meter.go
- x/tally/keeper/gas_meter_test.go
- x/tally/keeper/tally_vm.go
- x/tally/keeper/tally_vm_test.go
- x/tally/types/abci_types.go
- x/tally/types/filters.go
- x/tally/types/filters_util.go
- x/tally/types/gas_meter.go
PR #538 introduced sorting data proxy and executor payout lists with entropy in order to ensure some level of fairness when the contract goes through the lists in order until the fees are exhausted. This change, however, did not address the scenario where divergent gas reports involve multiple lowest reporters. To address both issues, this PR moves the executor sorting with entropy from the payout message construction phase to the beginning of tally process of a given request.
> Refactor reveal sorting in tally

- app/abci/helpers_test.go
- app/app.go
- app/utils/seda_config.go
- app/utils/seda_keys.go
- app/utils/seda_keys_test.go
- cmd/sedad/cmd/config.go
- e2e/e2e_test.go
- e2e/validator.go
- scripts/testnet/create_genesis.sh
- x/pubkey/client/cli/keyfile.go
- x/staking/simulation/operations.go
We have been using the same directory as the private validator key file for storing and finding the SEDA key file since this path is provided by the CometBFT configuration. Since the SEDA key file is used by the application, this PR creates a new configuration to the `app.toml` file. The default location for the key file remains the same at `$NODE_HOME/config/seda_keys.json`.
This configuration value can be queried with the following command:
```
$ sedad config get app seda.seda_key_file             
"config/seda_keys.json"
```
> Custom app config for SEDA key file path

- cmd/sedad/cmd/config.go
- interchaintest/seda_chain.go
- scripts/local_multi_setup.sh
- x/pubkey/client/cli/keyfile.go
-  Do not read environment variable for encryption key when generating SEDA Keys. 
- From my experience, using the environment variable value as an encryption key when generating SEDA Keys was prone to cause confusion. Now to use a custom encryption key, you have to pass the custom encryption flag and provide the key when prompted. 
- In pre-upgrade, return success without migrating if "seda" app config already exists.
- Fix local multi validator setup script.
> Minor refactor of SEDA Keys and config

- app/abci/handlers.go
- app/app.go
- cmd/sedad/cmd/config.go
- interchaintest/chain_start_test.go
- interchaintest/ica_test.go
- interchaintest/seda_chain.go
- interchaintest/setup.go
- interchaintest/state_sync_test.go
- scripts/local_multi_setup.sh
- x/pubkey/types/params.go
- Panic at startup if signer loading fails when it is enabled in config.
- Fix pre-upgrade logic.
- ExtendVote should not fail even if signer reload due to mismatch fails.
> Improve SEDA signer configuration logic

- x/pubkey/types/params.go
Revert the parameter value we changed for test release
> Revert change in default proving scheme activation delay

- .github/PULL_REQUEST_TEMPLATE.md
- app/utils/seda_keys.go
There were requests from validators to support configuring the encryption key for a SEDA key file through a file in addition to an environment variable. This PR adds a new environment variable `FILE_SEDA_KEYS_ENCRYPTION_KEY` whose value, if present, would indicate a path to the file that contains an encryption key to the SEDA key file.
Also adds a dependency list to the pull request template.
> Support setting SEDA key file encryption key through a file

- cmd/sedad/gentx/gentx.go
- go.mod
- go.sum
- x/vesting/types/codec.go
- x/vesting/types/vesting.go
Upgrading tallyvm to v2.4.0, which fixes the issue where the vm returns a zero exit code even when the memory allocation exceeds the capacity.
> Upgrade tallyvm to v2.4.0

- app/upgrades/mainnet/v1/constants.go
- x/tally/keeper/endblock.go
- x/tally/types/telemetry.go
- Removes core contract parameter values from instantiate msg so that the contract parameters are initialized to the default values defined in the contract.
- Telemetry sets a gauge under key `seda_tally_end_block_dr_flow_halt` to 1 if DR flow halts. It's set back to 0 when `ProcessTallies()` is executed successfully.
> Update core contract instantiate msg

- app/upgrades.go
- app/upgrades/testnet/v1.0.0-rc.6/constants.go
- x/tally/keeper/endblock.go
- x/tally/keeper/endblock_test.go
- x/tally/types/data_result.go
Previously when we introduced the paused contract and fallback results and refactored the payouts we made a mistake which caused the DRs to not be removed from the contract.
Always create an entry in the processedRequests map (empty slice means full refund)
Have the MarkX methods set the result id
Add the testnet upgrade handler for rc.6
Expand on the unit tests to correctly check that no new results are being created and that funds are distributed correctly.
N.A.
> Correctly process data requests when the contract is paused

- proto/sedachain/core/v1/genesis.proto
- testutil/integration.go
- x/core/keeper/core_benchmark_test.go
- x/core/keeper/endblock.go
- x/core/keeper/genesis.go
- x/core/keeper/genesis_test.go
- x/core/keeper/keeper.go
- x/core/keeper/owner.go
- x/core/keeper/testutil/fixture.go
- x/core/keeper/timeout_queue.go
- x/core/types/genesis.pb.go
- x/core/types/hash_sort.go
Add genesis state so we can import and export the core module state.
Integration testing to simulate a lot of data requests followed by comparison of states before and after export and import. The test also exports states from two different instantiations of the app and compares the two exported genesis states.
Related: #593
> x/core GenesisState 

- app/upgrades/mainnet/v1.1.0/upgrade.go
- x/core/types/staker_indexing.go
Taking into account that staker count store is accessed by the upgrade handler without initialization. 
Also, the "owner" key check should be a strict match to avoid matching with "pending_owner".
> Fix core upgrade handler bug

- x/core/keeper/data_request_tests/query_by_status_test.go
- x/core/types/data_request.go
- x/core/types/data_request_indexing.go
To have the DRs in the correct order when queried.
- The Index was not correctly accounting for the hex difference so lastSeenIndex would be null from strings due to wrong byte length size.
- The Index now properly sorts by oldest block to newest block(height inversion).
- Adjusted the query to do descending order.
The tests around the query now pass.
[data-proxy]:https://github.com/sedaprotocol/seda-data-proxy
[evm-contracts]:https://github.com/sedaprotocol/seda-evm-contracts
[sdk]: https://github.com/sedaprotocol/seda-sdk
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[solver]:https://github.com/sedaprotocol/seda-solver
[chain-indexer-plugin]: https://github.com/sedaprotocol/seda-chain
[explorer/indexer]: …
> Fix: dr sort order and pagination
