sedaprotocol/seda-chain

x/wasm-storage/keeper/common_test.go, x/wasm-storage/keeper/keeper.go, x/wasm-storage/keeper/keeper_test.go, x/wasm-storage/keeper/msg_server_test.go
Add Test for Keeper wasm-storage
=> feat(wasm-storage): keeper test wasm-storage

.github/workflows/realease.yml, .github/workflows/test.yml, .gitignore, .goreleaser.yml
(Write your motivation here)
(Write your explanation here)
(Write your test plan here)
(Link your related PRs and Issues here)
=> chore: add release gh action

.github/workflows/realease.yml
Small fix, I will add release notes later.
=> chore: fix release notes

go.mod, scripts/testnet/build_genesis_state.sh, scripts/testnet/config_example.sh, scripts/testnet/create_genesis.sh, scripts/testnet/members.json, scripts/testnet/policy.json, scripts/testnet/upload_and_start.sh
Updates scripts to current testnet configurations
Also closes #203
=> chore: update testnet script

app/upgrades/testnet/v1/constants.go
Adding an upgrade handler for upgrade from v0.0.6 to v0.0.7
=> chore: add upgrade handler

README.md, SECURITY.md
This PR adds the `SECURITY.md` file, outlining the security policy for the SEDA chain.
The file provides guidelines for reporting vulnerabilities, severity classification, and the vulnerability disclosure process.
=> docs: add SECURITY.md

scripts/testnet/create_genesis.sh, x/wasm-storage/genesis.go, x/wasm-storage/keeper/keeper.go, x/wasm-storage/keeper/msg_server.go
Fixiing initialization issue in wasm-storage collections.
=> fix: fix collections init issue

scripts/local_multi_setup.sh, scripts/local_setup.sh, scripts/testnet/build_genesis_state.sh, scripts/testnet/config_example.sh, scripts/testnet/create_genesis.sh, scripts/testnet/upload_and_start.sh
- Fix the issue where the genesis state of group module was not set properly
- Ability to download an artifact
- Adding more parameters to configuration 
- Cleaning code
See Notion doc on Node Operation for more detailed instructions.
=> refactor: updating deployment scripts

.gitignore, go.mod, go.sum, x/wasm-storage/keeper/abci_test.go, x/wasm-storage/keeper/filter.go, x/wasm-storage/keeper/filter_test.go, x/wasm-storage/types/codec.go, x/wasm-storage/types/codec_test.go, x/wasm-storage/types/errors.go
Introduce filter type Mode. Also closes this issue https://github.com/sedaprotocol/seda-chain/issues/286
Unit tests included.
https://github.com/sedaprotocol/seda-chain/issues/286
=> feat: filter type Mode

proto/sedachain/data_proxy/v1/data_proxy.proto, proto/sedachain/data_proxy/v1/tx.proto, x/data-proxy/keeper/abci.go, x/data-proxy/keeper/keeper.go, x/data-proxy/keeper/keeper_test.go, x/data-proxy/module.go, x/data-proxy/types/data_proxy.pb.go, x/data-proxy/types/tx.pb.go
Updated the wording of the update height to better reflect that it is executed at endblock.
Fairly straightforward implementation.
Added a slightly hacky test for the endblock logic. Would like to receive tips on how this could be improved.
Part-of: #316
=> Add fee update endBlock handling

.golangci.yml, x/tally/keeper/abci.go, x/tally/keeper/abci_test.go, x/tally/keeper/integration_test.go, x/tally/types/abci_types.go, x/tally/types/filters.go
=> feat(x/tally): expire data requests

x/batching/keeper/querier.go
- For query of all batches, do not return batches without signatures.
=> refactor(batching): Batch query refactor

plugins/indexing/pluginaws/sqs_client.go
Better insights into errors returned by SQS.
N.A.
N.A.
N.A.
=> Add extra logs for SQS errors

x/tally/types/params.go
Implement the findings from Jon's experimentation.
N.A.
N.A.
https://github.com/sedaprotocol/seda-overlay/pull/267
=> Lower default max tally gas limit

cmd/sedad/cmd/init_cmds.go, scripts/testnet/setup_node.sh
Adding support for chaosnet for the join command.
=> Preparation for chaosnet

.github/workflows/test.yml, Makefile, codecov.yml, x/batching/keeper/genesis_test.go, x/batching/types/batch_test.go, x/batching/types/data_result.go, x/batching/types/data_result_test.go, x/batching/types/genesis.go, x/batching/types/genesis_test.go
- Tests for genesis state export and import
- Tests for batch ID computation
- `ValidateGenesis` that checks the validity of batch ID based on tree roots
=> Improve batching module testing

app/abci/vote_extension_test.go
Adds test cases involving malicious proposer scenarios to the existing ABCI++ handler testing. 
- Proposer injects empty or arbitrary vote extension (=> vote extension signature verification fails)
- Proposer injects additional vote (=> comparison to last commit data fails)
- Proposer replaces a vote with some arbitrary vote (=> comparison to last commit data fails)
=> Test vote extension under malicious proposer scenarios

go.mod, go.sum
Addresses ISA-2025-001 and ISA-2025-002.
N.A.
Running on testnet.
N.A.
=> Update sdk to v0.50.13 and ibc-go to v8.7.0

x/tally/keeper/filter.go, x/tally/keeper/filter_test.go
Make sure the correct executors get rewarded for honest participation.
Make the comparison inclusive.
Added a unit test case that failed without the fix.
Targeting open PR to make merging easier.
=> Correctly identify consensus in error for exactly 2/3rds

x/batching/module.go, x/data-proxy/module.go, x/pubkey/module.go, x/slashing/module.go, x/staking/module.go, x/tally/module.go, x/vesting/module.go, x/wasm-storage/module.go
Use the same interface method for registering services for consistency.
Checked that the vesting module messages for creating a vesting account and clawbacking work in a local setup.
=> Consistent interface for registering services

go.mod, go.sum
Includes many fixes to avoid gas abuse or panics.
N.A.
Tests still pass.
N.A.
=> Bump wasm-vm to v2.3.0-rc.2

Makefile, README.md, e2e/e2e_setup_test.go, go.mod, go.sum, interchaintest/chain_core_test.go, interchaintest/chain_start_test.go, interchaintest/ibc_conformance_test.go, interchaintest/ibc_transfer_test.go, interchaintest/ica_test.go, interchaintest/pfm_test.go, interchaintest/sdk_boundaries_test.go, interchaintest/seda_chain.go, interchaintest/setup.go, interchaintest/state_sync_test.go
- Include fix for std_out and std_err logs not being processed completely.
- Interchain test refactor to customize setup process for SEDA Chain. Had to copy a lot of code from the interchaintest codebase, but this setup could be useful in the future as well.
N.A.
Pipeline.
N.A.
=> Update tallyvm to v2.3.0-rc.3 & interchain test refactor

README.md, go.mod, go.sum
Include fix for gas metering not correctly accounting for certain branch structures.
N.A.
The pipeline will tell.
N.A.
=> chore(x/tally): update tallyvm to v2.3.0

x/core/keeper/core_benchmark_test.go, x/core/keeper/core_test.go, x/core/keeper/endblock.go, x/core/keeper/endblock_test.go, x/core/keeper/gas_meter.go, x/core/keeper/keeper.go, x/core/keeper/msg_server_dr.go, x/core/keeper/testutil/fixture_helpers.go, x/core/keeper/timeout_queue.go
Adds the remaining missing pausability logic.
- Adds pausability to DR txs.
- Adds the old tally pause contract test back in.
- Fixes some bugs found with pausability.
- Fixes a bugs skipping other timed out drs.
- Fixes incorrectly calculated dr reveal timeout.
- removes testing arg from fixture functions since fixture has testing in it.
Will be done in a future PR :).
[data-proxy]:https://github.com/sedaprotocol/seda-data-proxy
[evm-contracts]:https://github.com/sedaprotocol/seda-evm-contracts
[sdk]: https://github.com/sedaprotocol/seda-sdk
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[solver]:https://github.com/sedaprotocol/seda-solver
[chain-indexer-plugin]: https://github.com/sedaprotocol/seda-chain …
=> feat(core): add the remaining pausability behavior

x/core/client/cli/query.go, x/core/client/cli/tx.go
CLI methods for the core where it makes sense.
Adds CLI commands for owner, staker and posting a data request.
Things like staking, committing, and revealing are ignored since those are a more complex flow.
Tested most of the manually.
[data-proxy]:https://github.com/sedaprotocol/seda-data-proxy
[evm-contracts]:https://github.com/sedaprotocol/seda-evm-contracts
[sdk]: https://github.com/sedaprotocol/seda-sdk
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[solver]:https://github.com/sedaprotocol/seda-solver
[chain-indexer-plugin]: https://github.com/sedaprotocol/seda-chain
[explorer/indexer]: https://github.com/sedaprotocol/seda-explorer
Think about the changes (msgs, events, limits, etc.) made in this PR and see if …
=> Feat: core cli
